uint8 output
uint8 OUTPUT_BOTH = 0x83
uint8 OUTPUT_YAW = 0x81
uint8 OUTPUT_YAWRATE = 0x82

uint8 mode
uint8 MODE_STOP = 0x39
uint8 MODE_ONE_TIME = 0x30
uint8 MODE_CONTINUE_20MS = 0x32
uint8 MODE_CONTINUE_50MS = 0x33
uint8 MODE_CONTINUE_100MS = 0x34
uint8 MODE_CONTINUE_200MS = 0x35
uint8 MODE_CONTINUE_250MS = 0x36
uint8 MODE_CONTINUE_500MS = 0x37
uint8 MODE_CONTINUE_1000MS = 0x38

---

int8 result
int8 RESULT_FAIL = -1
int8 RESULT_DONE = 0